id2label = {18: 'Pediatrics',
            13: 'Pulmonary Disorders',
            8: 'Hematology and Oncology',
            14: 'Cardiovascular Disorders',
            12: 'Neurologic Disorders',
            15: 'Critical Care Medicine',
            17: 'Gynecology and Obstetrics',
            22: 'Special Subjects',
            21: 'Injuries; Poisoning',
            19: 'Geriatrics',
            0: 'Nutritional Disorders',
            7: 'Endocrine and Metabolic Disorders',
            16: 'Genitourinary Disorders',
            3: 'Musculoskeletal and Connective Tissue Disorders',
            4: 'Ear, Nose, Throat, and Dental Disorders',
            2: 'Hepatic and Biliary Disorders',
            6: 'Dermatologic Disorders',
            10: 'Infectious Diseases',
            1: 'Gastrointestinal Disorders',
            11: 'Psychiatric Disorders',
            5: 'Eye Disorders',
            9: 'Immunology; Allergic Disorders',
            20: 'Clinical Pharmacology'}
label2id = {'Pediatrics': 18,
            'Pulmonary Disorders': 13,
            'Hematology and Oncology': 8,
            'Cardiovascular Disorders': 14,
            'Neurologic Disorders': 12,
            'Critical Care Medicine': 15,
            'Gynecology and Obstetrics': 17,
            'Special Subjects': 22,
            'Injuries; Poisoning': 21,
            'Geriatrics': 19,
            'Nutritional Disorders': 0,
            'Endocrine and Metabolic Disorders': 7,
            'Genitourinary Disorders': 16,
            'Musculoskeletal and Connective Tissue Disorders': 3,
            'Ear, Nose, Throat, and Dental Disorders': 4,
            'Hepatic and Biliary Disorders': 2,
            'Dermatologic Disorders': 6,
            'Infectious Diseases': 10,
            'Gastrointestinal Disorders': 1,
            'Psychiatric Disorders': 11,
            'Eye Disorders': 5,
            'Immunology; Allergic Disorders': 9,
            'Clinical Pharmacology': 20}
